import { useState } from "react";

export const projects = [
  {
    title: 'Online mahalla',
    description: "Online-mahalla website is a responsive website built using Reactjs JS HTML CSS.",
      image: '/images/8.png',
      tags: ['HTML', 'CSS', 'Javascript', 'ReactJs'],
    source: 'https://github.com/ergashevislomjon/online-mahalla',
    visit: 'https://online-mahalla.netlify.app/',
    id: 7,
  },

  {
    title: 'Chat AI Application',
    description:"With an elegant user interface that resembles the Chat GPT app, communication with advanced GPT 3 model API.",
    image: '/images/2.jpg',
    tags: ['React', 'JavaScript', 'Firebase'],
    source: 'https://github.com/ergashevislomjon/chat_open_ai',
    visit: 'https://chat-openai-uz.vercel.app/',
    id: 1,
  },
  {
    title: 'Plants Website',
    description: "Responsive Plants Website Design Using HTML CSS & JavaScript .",
      image: '/images/7.png',
      tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/Plants_website',
    visit: 'https://plants-web-uz.netlify.app/',
    id: 6,
  },
  {
    title: 'Namoz vaqtlari',
    description: "You can find out prayer times in all regions of Uzbekistan through this site.",
      image: '/images/11.png',
      tags: ['HTML', 'CSS', 'Javascript', 'RestAPI'],
    source: 'https://github.com/ergashevislomjon/Namoz-times',
    visit: 'https://namoz-time.netlify.app/',
    id: 10,
  },
  {
    title: 'Bookshelter',
    description: "A website to find and read books online..",
      image: '/images/9.png',
      tags: ['HTML', 'CSS', 'Javascript', 'RestAPI'],
    source: 'https://github.com/ergashevislomjon/google-books',
    visit: 'https://bookshelter-search.netlify.app/',
    id: 8,
  },
  {
    title: 'AI Image Generator',
    description: "Sun'iy intellekt asosida o'zingizning rasmingizni yarating.",
    image: '/images/1.jpg',
    tags: ['NodeJs', 'ExpressJs', 'MongoDB', 'Mongoose', 'ReactJs','HTML CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/image_ai',
    visit: 'https://image-ai-five.vercel.app/',
    id: 15,
  },
  {
    title: 'Movies website',
    description: "A website where you can find all movies and sort your favorite movies.",
    image: '/images/16.png',
    tags: ['HTML', 'CSS', 'Javascript', 'ReactJs', 'Rest API'],
    source: 'https://github.com/ergashevislomjon/movies',
    visit: 'https://movies-uzb.netlify.app/',
    id: 16,
  },
  {
    title: 'Weather app',
    description: "You can get city weather information in this app.",
      image: '/images/14.png',
      tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/Weather_app',
    visit: 'https://weather-app-islomjon.netlify.app/',
    id: 12,
  },
  {
    title: 'Countries of the world',
    description: "You can get information about all the countries of the world through this app.",
      image: '/images/13.png',
      tags: ['HTML', 'CSS', 'Javascript', 'RestApi'],
    source: 'https://github.com/ergashevislomjon/country',
    visit: 'https://all-country-data.netlify.app/',
    id: 13,
  },
  {
    title: 'Mytube app',
    description: "This is an app that uses the Youtube api. YouTube videos can be searched and viewed.",
      image: '/images/15.png',
      tags: ['HTML', 'CSS', 'Javascript', 'ReactJs', 'RestApi'],
    source: 'https://github.com/ergashevislomjon',
    visit: 'https://mytube-uz.netlify.app/',
    id: 14,
  },
  {
    title: 'Restaurant website ',
    description: "A restaurant website where you can book a restaurant.",
    image: '/images/17.png',
    tags: ['HTML', 'CSS', 'Javascript', 'ReactJs'],
    source: 'https://github.com/ergashevislomjon/gerIicht-food',
    visit: 'https://geriicht-food.netlify.app/',
    id: 18,
  },
  {
    title: 'Millor coffee website ',
    description: "Millor coffee website. Millor coffee website.",
    image: '/images/19.png',
    tags: ['HTML', 'CSS', 'Javascript', 'ReactJs'],
    source: 'https://github.com/ergashevislomjon/millor-coffee',
    visit: 'https://millor-coffee.vercel.app/',
    id: 19,
  },
  {
    title: 'Google Search',
    description: "A google search that doesn't differ from Google. Almost all Google search functions are available.",
      image: '/images/3.jpg',
      tags: ['React', 'Javascript', 'Tailwind'],
    source: 'https://github.com/ergashevislomjon/google-clone',
    visit: 'https://google-z.netlify.app/',
    id: 2,
  },
  {
    title: 'Tasty Food',
    description: "Responsive Website Design Using HTML CSS And JavaScript. Website Restaurant Light/Dark mode",
      image: '/images/6.png',
      tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/Tasty_food',
    visit: 'https://tastyfood-uz.netlify.app/',
    id: 5,
  },
  {
    title: 'Learning Center',
    description: "Website using HTML CSS JS for learning center.",
      image: '/images/10.png',
      tags: ['HTML', 'CSS', 'Javascript', 'ReactJs'],
    source: 'https://github.com/ergashevislomjon/Learning-center',
    visit: 'https://learning-centeruz.netlify.app/',
    id: 9,
  },
  {
    title: 'Super Fast Food Delivery Service',
    description: "Super Fast Food Delivery service website.",
      image: '/images/12.png',
      tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/Namoz-times',
    visit: 'https://efood-uz.netlify.app/',
    id: 11,
  },
  {
    title: 'Techgear website',
    description: "Website for a hardware store.",
    image: '/images/18.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/ergashevislomjon/techgear',
    visit: 'https://techgear-uz.netlify.app/',
    id: 17,
  },
  
  
];

export const TimeLineData = [
  { year: 2021, text: 'Started my journey', },
  { year: 2021, text: 'Worked as a freelance developer', },
  { year: 2022, text: 'I finished the Fullstack course in Najot ta\'lim', },
  { year: 2022, text: 'I started working at Abutech company', },
];
